export const colorDatas = {
  simpleColors: [
    "red",
    "orange",
    "purple",
    "yellow",
    "green",
    "blue",
    "gray",
    "indigo",
    "violet",
    "brown",
    "pink",
    "chocolate",
    "teal",
    "silver",
    "maroon",
    "aquamarine",
    "coral",
    "fuchsia",
    "wheat",
    "lime",
    "crimson",
    "khaki",
    "magenta",
    "plum",
    "olive",
    "cyan",
    "grey",
  ],

  hexColors: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "A", "B", "C", "D", "E", "F"],
};
